export const AdminController = {
    SearchForUser:`Admin/Usersearch`,
    GetBlog:(id:any)=>`Admin/${id}/GetAllBlogDetails`,
    GetComplaintDetails:(id:any)=>`Admin/${id}/GetComplaintDetails`,
    GetUserComplaints:(id:any)=>`Admin/${id}/GetUserComplaints`,
    GetServiceDetails:(id:any)=>`Admin/${id}/GetServiceDetails`,
    GetUserData:(id:any)=>`Admin/Usersearch/${id}`,
    BlockUser:(id:any)=>`Admin/SuspendUser/${id}`,
    UnBlockUser:(id:any)=>`Admin/UnSuspendUser/${id}`,
    DeleteUser:(id:any)=>`Admin/DeleteUSer/${id}`,
    GetAllBlogs:`Admin/GetAllMainBlogs`,
    GetAllBoxesForAdmin:`Admin/GetAllBoxesForAdmin`,
    GetAllLogos:`Admin/GetAllLogos`,
    GetAllServices:`Admin/GetAllServices`,
    GetAllComplaintsForAdmins:`Admin/GetAllComplaintsForAdmins`,
    DeleteBlog:(id:any)=>`Admin/${id}/DeleteBlog`,
    DeleteBoxeData:(id:any)=>`Admin/DeleteBoxeData/${id}`,
    DeleteHomeLogo:(id:any)=>`Admin/DeleteHomeLogo?LogoId=${id}`,
    DeleteService:(id:any)=>`Admin/${id}/DeleteService`,
    AddMainBlog:`Admin/AddMainBlog`,
    AddLogo:`Admin/AddLogo`,
    AddHomeBoxesData:`Admin/AddHomeBoxesData`,
    AddMainServices:`Admin/AddMainServices`,
    Addattachment:`Admin/AddBlogAttachments`,
    AddServiceAttachments:`Admin/AddServiceAttachments`,
    AddComplaintReply:`Admin/AddComplaintReply`,
    UpdatePublishedStatus:(BlogId:any)=>`Admin/${BlogId}/UpdateBlogStatusPublished`,
    UpdateBoxStatus:(id:any)=>`Admin/UpdateBoxStatus/${id}`,
    UpdateHomeLogoStatus:(LogoId:any)=>`Admin/UpdateHomeLogoStatus?LogoId=${LogoId}`,
    UpdateUsingInHomeStatus:(categoryId:any)=>`Admin/UpdateCategoryusingstate/${categoryId}`,
    UpdateRecommendedStatus:(freelancerId:any)=>`Admin/${freelancerId}/UpdateRecommendedStatus`,
    UpdateServiceStatusPublished:(serviceId:any)=>`Admin/${serviceId}/UpdateServiceStatusPublished`,
    GetAllCategories:`Admin/GetAllCategoriesWithItsDetails`,
    AddCategory:`Admin/AddCategoriesWithItsDetails`,
    AddSubcategory:`Admin/AddSubcategory`,
    UpdateMainBlog:`Admin/UpdateMainBlog`,
    UpdateCategories:(categoryId:any)=>`Admin/${categoryId}/UpdateCategory`,
    UpdateSubCategory:(categoryId:any)=>`Admin/${categoryId}/UpdateSubCategory`,
    DeleteCategory:(categoryId:any)=>`Admin/${categoryId}/DeleteCategory`,
    DeleteSubCategory:(SubcategoryId :any)=>`Admin/${SubcategoryId}/DeleteSubCategory`,
    GetSubCategory:(SubcategoryId :any)=>`Admin/GetSubCategory/${SubcategoryId}`,

   
  }